name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git config --global credential.helper store
          echo "https://user:$HF_TOKEN@huggingface.co" > ~/.git-credentials

          git remote add hf https://huggingface.co/spaces/Amitkarar/YTvideoandURLsummarization
          git push --force hf main
