name: Sync To Hub

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Modify file
        run: echo "Updated on $(date)" >> sync.log

      - name: Commit and push
        run: |
          git add .
          git commit -m "Auto update" || echo "Nothing to commit"
          git push
